name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: release extension
        run: npm run release
      - name: production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-wubi
          retention-days: 7
          path: dist/web-wubi.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/web-wubi.zip
